
/*
 * 
 */

package com.exjoy.study;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0
 * Wed Feb 01 10:50:04 CST 2012
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "TestWebServiceJdkService", 
                  wsdlLocation = "http://localhost:10001/hello?wsdl",
                  targetNamespace = "http://www.exjoy.cn/study/webservice/jdk") 
public class TestWebServiceJdkService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.exjoy.cn/study/webservice/jdk", "TestWebServiceJdkService");
    public final static QName TestWebServiceJdkPort = new QName("http://www.exjoy.cn/study/webservice/jdk", "TestWebServiceJdkPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:10001/hello?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:10001/hello?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TestWebServiceJdkService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceJdkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceJdkService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns TestWebServiceJdk
     */
    @WebEndpoint(name = "TestWebServiceJdkPort")
    public TestWebServiceJdk getTestWebServiceJdkPort() {
        return super.getPort(TestWebServiceJdkPort, TestWebServiceJdk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceJdk
     */
    @WebEndpoint(name = "TestWebServiceJdkPort")
    public TestWebServiceJdk getTestWebServiceJdkPort(WebServiceFeature... features) {
        return super.getPort(TestWebServiceJdkPort, TestWebServiceJdk.class, features);
    }

}
