package com.exjoy.study;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Wed Feb 01 10:50:04 CST 2012
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://www.exjoy.cn/study/webservice/jdk", name = "TestWebServiceJdk")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebServiceJdk {

    @WebResult(name = "x", targetNamespace = "")
    @RequestWrapper(localName = "ffff", targetNamespace = "http://www.exjoy.cn/study/webservice/jdk", className = "com.exjoy.study.Ffff")
    @WebMethod(action = "ddd")
    @ResponseWrapper(localName = "ffffResponse", targetNamespace = "http://www.exjoy.cn/study/webservice/jdk", className = "com.exjoy.study.FfffResponse")
    public java.lang.String ffff(
        @WebParam(name = "kkk", targetNamespace = "")
        java.lang.String kkk
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "helloComplexSerivce", targetNamespace = "http://www.exjoy.cn/study/webservice/jdk", className = "com.exjoy.study.HelloComplexSerivce")
    @WebMethod
    @ResponseWrapper(localName = "helloComplexSerivceResponse", targetNamespace = "http://www.exjoy.cn/study/webservice/jdk", className = "com.exjoy.study.HelloComplexSerivceResponse")
    public com.exjoy.study.WsResponse helloComplexSerivce(
        @WebParam(name = "arg0", targetNamespace = "")
        com.exjoy.study.WsRequset arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
